version: '3.8'

services:
  frontend:
    build:
      context: u-front
    ports:
      - "3000:3000"
    depends_on:
      - backend
    volumes:
      - ./u-front:/app

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5433:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=uniMarket
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/postgresql/data
      - pgdata:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"

  backend:
    restart: always
    build:
      context: u-back
    ports:
      - "5001:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - HOST=0.0.0.0
    depends_on:
      - db
      - redis
volumes:
  pgdata: