version: '3.8'

services:
  frontend:
    build:
      context: u-front
    ports:
      - "8080:8080"
    volumes:
      - ./u-front:/app
    depends_on:
      - backend

  backend:
    build:
      context: u-back
    ports:
      - "5000:5000"
    environment:
      - FLASK_APP=app.py
      - FLASK_ENV=development
      - HOST=0.0.0.0
    volumes:
      - ./u-back:/app
    depends_on:
      - db
      - redis

  db:
    image: postgres:latest
    restart: always
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_PASSWORD=qwerty123
      - POSTGRES_DB=uniMarket
      - POSTGRES_USER=postgres
    volumes:
      - ./data:/var/lib/postgresql/data

  redis:
    image: redis:latest
    restart: always
    ports:
      - "6379:6379"
